### ISSUE TITLE
Error when trying to create a new network

### ISSUE THREAD

**Issue by ruipedrodias94** [synechron-finlabs/quorum-maker#108]
I'm facing an error when trying to create a new network.

Steps to reproduce:
In ./setup
Option: 1
      Ip of this node: 10.3.4.29
      All other options set to default

![Capture](https://user-images.githubusercontent.com/10145055/58805294-b458ee00-860b-11e9-81cc-8540d6567d9e.PNG)

**Comment by PavithraViswanathan12** [comment]
Use some other RPC port like 23000

**Comment by ruipedrodias94** [comment]
Sorry for the late reply, but I managed to recover from my problem. It seems that my machine clocks weren't synched. The solution that I found was to sync the clocks with NTP.

Thank you!
