### ISSUE TITLE
Deploying contracts fails in production-like-environment

### ISSUE THREAD

**Issue by erNail** [synechron-finlabs/quorum-maker#11]
Hi,

i've created nodes withouth docker-compose support, for a production-like environment. I can start the bootnode without problems, this is the output of `$ docker ps`:

```
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS                                                                                                                                                      NAMES
82f85324ea37        syneblock/quorum    "./start_node1.sh"   3 seconds ago       Up 2 seconds        0.0.0.0:9000->9000/tcp, 0.0.0.0:10000->10000/tcp, 0.0.0.0:22000->22000/tcp, 0.0.0.0:10000->10000/udp, 0.0.0.0:30000->30000/tcp, 0.0.0.0:30000->30000/udp   gallant_morse
```

When i'm now trying to deploy a contract, via truffle or cakeshop, the process simply freezes. Any idea why ? When creating nodes with docker-compose support everything works fine.

**Comment by dhyansraj** [comment]
How many nodes you created ? Are they connecting each other successfully? If the deployment freezes, it is normally an issue with gas. Also, would you be able to try to deploy a simple contract from the geth console if nothing else works? you can attach to a node using docker exec and do 'geth attach qdata/geth.ipc' and loadScript('...')

**Comment by ijazm** [comment]
Deploying contract in production like environment fails, the process freeze as mentioned in the above issue. In the geth console getting an error
Unable to vote: Node is not configured for voting quorum-maker
