### ISSUE TITLE
data structure

### ISSUE THREAD

**Issue by PavithraViswanathan12** [synechron-finlabs/quorum-maker#110]
When a contract is deployed in quorum network where the data is stored ?  Is it uses any inbuilt level db or some other databases?
Or should I manually write code to store it in level db?

**Comment by abhayar** [comment]
@PavithraViswanathan12  Yes, it uses inbuilt level db to store quorum network data.

**Comment by PavithraViswanathan12** [comment]
thanks!

**Comment by abhayar** [comment]
closed  #110
