### ISSUE TITLE
Following Wiki install steps directly leads to nodes hanging after "Adding Whitelist IPs"

### ISSUE THREAD

**Issue by fmhall** [synechron-finlabs/quorum-maker#122]
launching a network on one machine with `setup.sh` with defaults on option 4, then doing a `docker-compose` gives this output:

```
Starting node1 ... done
Starting node3 ... done
Starting node2 ... done
Attaching to node1, node2, node3
node1    | {"level":"info","msg":"Node Manager listening on :22004...","time":"2019-09-11T21:33:44Z"}
node2    | {"level":"info","msg":"Node Manager listening on :22004...","time":"2019-09-11T21:33:44Z"}
node3    | {"level":"info","msg":"Node Manager listening on :22004...","time":"2019-09-11T21:33:44Z"}
node1    | {"level":"info","msg":"Adding whitelisted IPs","time":"2019-09-11T21:33:45Z"}
node2    | {"level":"info","msg":"Adding whitelisted IPs","time":"2019-09-11T21:33:45Z"}
node3    | {"level":"info","msg":"Adding whitelisted IPs","time":"2019-09-11T21:33:45Z"}
```
And it never makes any progress from here. I also couldn't ping `http://localhost:22004`.

**Comment by abchowdhury** [comment]
Seems like Network Manager Contract is not getting deployed here. Is it a latest pull ?
Can you please tell me, which docker image you are using? You will find it in qm.variables.

**Comment by fredhampton** [comment]
I'am having the same issue.
The Docker image is 
dockerImage=syneblock/quorum-maker:2.2.1_2.6.2

**Comment by dwking2000** [comment]
same issue
docker logs -f 84c193530c580e5f18c210bc26c71a4ec97483c3c0631d345ecf6f8c32a53db4
{"level":"info","msg":"Node Manager listening on :22004...","time":"2019-11-29T22:09:22Z"}
{"level":"info","msg":"Adding whitelisted IPs","time":"2019-11-29T22:09:23Z"}

**Comment by fmhall** [comment]
The ports on the quorum-maker wiki are wrong.
There is actually an issue with quorum-maker though. If you run the normal ./setup.sh and create your own network (option 1), the program hangs and the node is never initialized after you put in the default inputs.
It works with 0.0.0.0 as the ip but nothing else

**Comment by dhyansraj** [comment]
The message you see is the last step in startup sequence. The nodes are in fact running. The ports are by default NOT exposed when creating a test network on localhost. Since test network uses, docker compose, the nodes are exposed using virtual IPs and hence can be accessed via IPs not using localhost. Eg. http://10.50.0.2:22004, http://10.50.0.3:22004 etc. This is clearly mentioned in the Wiki page. 

Also if you prefer to force expose ports on localhost, the the -e or --export flag while creating the Dev Network.
