### ISSUE TITLE
nodes hanging  when adding Whitelist IPs"

### ISSUE THREAD

**Issue by fredhampton** [synechron-finlabs/quorum-maker#129]
While Attempting to launch a network with option 4 the process hangs when adding white listed IPs.
The Docker image is
dockerImage=syneblock/quorum-maker:2.2.1_2.6.2

The output is below:

Attaching to node3, node1, node2
node3    | Waiting for Node 1 to deploy NetworkManager contract...
node1    | {"level":"info","msg":"Node Manager listening on :22004...","time":"2019-10-21T22:07:19Z"}
node2    | Waiting for Node 1 to deploy NetworkManager contract...
node1    | {"level":"info","msg":"Deploying Network Manager Contract","time":"2019-10-21T22:07:20Z"}
node3    | {"level":"info","msg":"Node Manager listening on :22004...","time":"2019-10-21T22:07:23Z"}
node1    | {"level":"info","msg":"Adding whitelisted IPs","time":"2019-10-21T22:07:23Z"}
node2    | {"level":"info","msg":"Node Manager listening on :22004...","time":"2019-10-21T22:07:24Z"}
node3    | {"level":"info","msg":"Adding whitelisted IPs","time":"2019-10-21T22:07:25Z"}
node2    | {"level":"info","msg":"Adding whitelisted IPs","time":"2019-10-21T22:07:26Z"}

**Comment by nickmi** [comment]
same with me

**Comment by nickmi** [comment]
> 
> 
> While Attempting to launch a network with option 4 the process hangs when adding white listed IPs.
> The Docker image is
> dockerImage=syneblock/quorum-maker:2.2.1_2.6.2
> 
> The output is below:
> 
> Attaching to node3, node1, node2
> node3 | Waiting for Node 1 to deploy NetworkManager contract...
> node1 | {"level":"info","msg":"Node Manager listening on :22004...","time":"2019-10-21T22:07:19Z"}
> node2 | Waiting for Node 1 to deploy NetworkManager contract...
> node1 | {"level":"info","msg":"Deploying Network Manager Contract","time":"2019-10-21T22:07:20Z"}
> node3 | {"level":"info","msg":"Node Manager listening on :22004...","time":"2019-10-21T22:07:23Z"}
> node1 | {"level":"info","msg":"Adding whitelisted IPs","time":"2019-10-21T22:07:23Z"}
> node2 | {"level":"info","msg":"Node Manager listening on :22004...","time":"2019-10-21T22:07:24Z"}
> node3 | {"level":"info","msg":"Adding whitelisted IPs","time":"2019-10-21T22:07:25Z"}
> node2 | {"level":"info","msg":"Adding whitelisted IPs","time":"2019-10-21T22:07:26Z"}

Have you found any solution to this problem ? I am also having trouble

**Comment by jonassunandar** [comment]
October 10, 2020. I have exactly the same issue.

**Comment by dhyansraj** [comment]
The message you see is the last step in startup sequence. The nodes are in fact running. The ports are by default NOT exposed when creating a test network on localhost. Since test network uses, docker compose, the nodes are exposed using virtual IPs and hence can be accessed via IPs not using localhost. Eg. http://10.50.0.2:22004, http://10.50.0.3:22004 etc. This is clearly mentioned in the Wiki page. 

Also if you prefer to force expose ports on localhost, use the -e or --export flag while creating the Dev Network.
