### ISSUE TITLE
Why do Accounts get locked quickly ?

### ISSUE THREAD

**Issue by moda20** [synechron-finlabs/quorum-maker#18]
hello !

This morning i ran my previously created nodes with this repo, and i used truffle to migrate (deploy) my contract, then used it as usual to test my contract and add upon it.

now i tried to run call some functions with web3 and it throws an error : `account locked`, i know the accounts get unlocked on the node start but do they stay for only 4 hours ? because that is the time difference between my calls .

**Comment by dhyansraj** [comment]
Closing as no longer relevant in the current release V2.0
