### ISSUE TITLE
Failed to setup Development/ Test Network

### ISSUE THREAD

**Issue by karthik137** [synechron-finlabs/quorum-maker#23]
I was trying to setup development network but looks like  `setup_network.sh` script file is missing. Is it still in development?. 

![quorumv2error](https://user-images.githubusercontent.com/19289544/40907688-3ae97a26-6802-11e8-8482-7c132f6ea0ef.png)

**Comment by rjbanner** [comment]
Yes Karthik.
We're integrating PBFT as well. Setup Development/Test Network will be available once PBFT is integrated

**Comment by rjbanner** [comment]
Hi Karthik,
We've added Setup Development/Test Network support on branch 2.1
You can check it out now

**Comment by karthik137** [comment]
Ok i will check it. Thanks @rjbanner.

**Comment by rjbanner** [comment]
Welcome @karthik137. Since we've updated the image on dockerhub could you kindly take the latest pull

**Comment by karthik137** [comment]
Sure

**Comment by dhyansraj** [comment]
This feature is available on V2.1 and soon be merged to master.
