### ISSUE TITLE
Run node in the background.

### ISSUE THREAD

**Issue by karthik137** [synechron-finlabs/quorum-maker#26]
How can i run start.sh in the background?. Thing is i want to run start.sh as a background process. ctrl+c exits the process and removes the container. Is there any way to run it in the background?.

**Comment by karthik137** [comment]
I ran it in the background by removing -it option from start.sh(main() and startNode() functions). I think we can give an option to run it in the background.

**Comment by dhyansraj** [comment]
docker containers can be send to background using Ctrl + p , Ctrl + q . 

https://stackoverflow.com/questions/19688314/how-do-you-attach-and-detach-from-dockers-process
