### ISSUE TITLE
Unable to deploy contracts via REMIX IDE

### ISSUE THREAD

**Issue by kggp1995** [synechron-finlabs/quorum-maker#29]
Hey team,

I had setup a network under `1) Create Network`; & able to access the network & node manager.

However, I'm unable to attach the web3 Provider under Remix IDE as per the result: 
`You can send transactions to A.B.C.D:22000`

**Comment by dhyansraj** [comment]
Can you deploy a contract from 'Compile & Deploy Contracts' tab on the top ? If that works, it could be just an IP reacheability issue. Is 159.65.80.74 your local machine? If so can you try to access using localhost? If not localhost, are you able to access Quorum Maker UI  at 159.65.80.74:22004 ?

**Comment by kggp1995** [comment]
@dhyansraj , thx for the swift reply. The node is a random stray public IP. Will try to mask it from now on..

But yes, the QMUI is visible at the url as specified.

Also, able to deploy contracts as mentioned above. However, while using the `A.B.C.D:22000` for Web3 Provider under Remix IDE I get the prompt: 
`Not possible to connect to the Web3 provider. Make sure the provider is running and a connection is open (via IPC or RPC).`

Am I missing something here?

**Comment by dhyansraj** [comment]
are you able to telnet A.B.C.D 22000 ?

**Comment by kggp1995** [comment]
Doesn't seem like it. This is what I got:

`Trying A.B.C.D...
Connected to A.B.C.D.
Escape character is '^]'.

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad RequestConnection closed by foreign host.`

**Comment by dhyansraj** [comment]
From QM UI, can you open the geth or constallation logs and see if everything working correct?

**Comment by kggp1995** [comment]
I see `INFO [] HTTP endpoint opened: http://0.0.0.0:22000 `

**Comment by dhyansraj** [comment]
0.0.0.0 mask allows connection from any IP. Can you connect from the localhost? In future, we will a web3 based test script for you to check connections easily.

**Comment by kggp1995** [comment]
Here's my `node/start_Testnet.sh`:

```
GLOBAL_ARGS="--raft --nodiscover --networkid $NETID --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --rpccorsdomain * --emitcheckpoints"
```

I have tried to override the Port as per the web3.js console order since I saw a few issues concerning the same [here](https://github.com/ethereum/remix-ide/issues/975). 

Still no luck...

**Comment by kggp1995** [comment]
@dhyansraj , Have you or anyone been able to connect a standalone node network to `http://remix.ethereum.org/` via web3 Provider or Metamask?

**Comment by dhyansraj** [comment]
We use truffle and that works well with QM. I will still check with our application development team, if anyone there use remix and QM together.

**Comment by kggp1995** [comment]
That'll be great help! 

Although with truffle, I had a few issues with `ruffle migrate --network development` migration suspending at deployment of `Migration.sol` contract.
This is a common issue observed with QNM as well. Following the truffle docs as mentioned, FYI. Has this been observed?

**Comment by rjbanner** [comment]
@kggp1995  Adding --rpccorsdomain "*"  to PRIVATE_CONFIG works. 
Can you try with the following:
PRIVATE_CONFIG=qdata/Testnet.ipc geth --verbosity 6 --datadir qdata $GLOBAL_ARGS --rpccorsdomain "*" --raftport $RA_PORT --rpcport $R_PORT --port $W_PORT --nat extip:$CURRENT_NODE_IP 2>>qdata/gethLogs/Testnet.log &

**Comment by rjbanner** [comment]
_@kggp1995  Adding --rpccorsdomain "*"  to PRIVATE_CONFIG works. 
Can you try with the following:
PRIVATE_CONFIG=qdata/Testnet.ipc geth --verbosity 6 --datadir qdata $GLOBAL_ARGS --rpccorsdomain "*" --raftport $RA_PORT --rpcport $R_PORT --port $W_PORT --nat extip:$CURRENT_NODE_IP 2>>qdata/gethLogs/Testnet.log &

**Comment by rjbanner** [comment]
Adding --rpccorsdomain "*" to PRIVATE_CONFIG works. Can you try with the following: PRIVATE_CONFIG=qdata/Testnet.ipc geth --verbosity 6 --datadir qdata $GLOBAL_ARGS --rpccorsdomain "*" --raftport $RA_PORT --rpcport $R_PORT --port $W_PORT --nat extip:$CURRENT_NODE_IP 2>>qdata/gethLogs/Testnet.log &

**Comment by rjbanner** [comment]
Adding --rpccorsdomain "*" to PRIVATE_CONFIG works. Can you try with the following: PRIVATE_CONFIG=qdata/Testnet.ipc geth --verbosity 6 --datadir qdata $GLOBAL_ARGS --rpccorsdomain "*" --raftport $RA_PORT --rpcport $R_PORT --port $W_PORT --nat extip:$CURRENT_NODE_IP 2>>qdata/gethLogs/Testnet.log &

**Comment by rjbanner** [comment]
_@kggp1995 Adding --rpccorsdomain "*" to PRIVATE_CONFIG works

**Comment by kggp1995** [comment]
Hi @rjbanner , thanks for the heads-up! This works for me. Will be discussing more about the developments in a PR very soon.
Also thx to @dhyansraj  for timely reply!

**Comment by nameskang** [comment]
Hi @rjbanner @kggp1995 , I also have the issue of being unable to deploy to a QM test network via truffle (stuck on deploying migrations). Adding --rpccorsdomain "*" to geth params has not solved the problem. RPC connection works - I can see the block getting generated in web UI and also the contract count increases so the Migrations contract is getting deployed for sure.
Latest version of QM and truffle. Using a development/test network of 3 nodes with exposed ports of first node via docker-compose.

**Comment by dhyansraj** [comment]
@nameskang  What URL are you  using to connect? Are you running on Mac or Windows?

**Comment by nameskang** [comment]
@dhyansraj The IPv4 address of my node and I'm using Mac. I tested the normal 7nodes Quorum example and it's also present there so the problem must be with Quorum or truffle. Anyway after fighting with this issue for a day, I've finally found a workaround [here](https://ethereum.stackexchange.com/questions/42130/truffle-migrate-stuck-at-first-migration#comment47713_42132). Do truffle migrations work for you with quorum (raft) with no issues?

**Comment by paliwalg** [comment]
Please check the transcationReceipt for the transactionHash you are getting back to confirm if the mining is happening.

I had a similar problem using Truffle with quorum, please check https://github.com/jpmorganchase/quorum/issues/86#issuecomment-315965611
