### ISSUE TITLE
Decode in Progress

### ISSUE THREAD

**Issue by horca17** [synechron-finlabs/quorum-maker#32]
Hello, we did more research and we create ower own Quorum Blockchain with 5 nodes (3yes-2no permissioned) on Linux and Mac from scratch and we are using Quorum-Maker option 3 to attach to an existing node, and as you said only some features are available. We can also deploy contracts. We are not using Docker nor Vagrant. We can do transaction privately and publicly using simplestorage.sol contract between nodes. Can you tell me more about this error Decode in Progress, we tried to move some ether from a pre-founded address to a no-funded one, any idea?
<img width="1280" alt="screen shot 2018-07-06 at 10 12 02 pm" src="https://user-images.githubusercontent.com/5912700/42405340-9b0ba268-816a-11e8-9d6b-a948ae8c7eeb.png">

**Comment by dhyansraj** [comment]
The decode functionality was not mature in 2.2. We have added more datatype support and code improvements in development branch. Please give a try by checking out development branch. We are planning for a 2.2.1 release soon, if you could wait.

**Comment by horca17** [comment]
Using attach to an existing node (option 3), on geth 1.7.2, Quorum 2.0.2, Quorum-Maker 2.3, compiled on my own private blockchain on my Mac without using Vagrant/Docker. Great job @synechron-finlabs .
<img width="1280" alt="screen shot 2018-07-22 at 9 16 00 am" src="https://user-images.githubusercontent.com/5912700/43045843-6027b4d8-8d96-11e8-8f67-f74df2e24978.png">

**Comment by rjbanner** [comment]
Hi @horca17. Ether transfer transactions should now be specified as such in the 2.3 Release
![whatsapp image 2018-07-22 at 19 33 30](https://user-images.githubusercontent.com/18460295/43046423-3796da08-8de6-11e8-8f3d-d47eef8535ef.jpeg)

**Comment by horca17** [comment]
Great!!!!!!


<img width="559" alt="screen shot 2018-07-22 at 11 36 21 am" src="https://user-images.githubusercontent.com/5912700/43046727-7fcfe776-8da3-11e8-9d2c-6defca80791e.png">
