### ISSUE TITLE
Smart contract storage issue

### ISSUE THREAD

**Issue by RomanG11** [synechron-finlabs/quorum-maker#33]
Hello. I tried to deploy the Solidity project to Quorum and find that one contract can call another contract function but it can't return value from storage contract. Example:

Contract First {

   bool public b = false;

    function setb () public {
        b = true;
    }
}

Contract Second {

First _storage;

constructor (address adr) public {
   _storage = adr;
}

function setb () public {
       _storage.setb();
    }

function getb() public view returns (bool){
      return _storage.b();
}
Contracts must be deployed separately.

So at first step I called setb() from contract 2, then checked b in first contract. It was true, but function getb() retuns 'false'. And this issue with all datatypes.

Maybe I must configure node to remove this issue, but I don't know what exactly must be done. Can you help me with this question?

**Comment by RomanG11** [comment]
Maybe I must configure node to remove this issue, but I don't know what exactly must be done. Can you help me with this question?

**Comment by dhyansraj** [comment]
Can you provide more details about your deployment? Have you deployed both contracts from Quorum Maker from the 'Compile & Deploy' tab? Or from an external tool? Are the transactions invoked privately or publicly ?

**Comment by RomanG11** [comment]
File 1:
pragma solidity ^0.4.18;

contract Contract1 {
  
  bool public a = true;

  function geta () public constant returns (bool) {
    return a; 
  }  
}

File2:
pragma solidity ^0.4.18;

/**
 * The Contract1 contract does this and that...
 */
contract Contract1 {
  bool public a;
  function geta () public constant returns (bool);
}


contract Contract2 {
  function geta () public constant returns (bool) {
    return cont.geta();
  }

  Contract1 public cont;

  function Contract2 (address addr) public {
    cont = Contract1(addr);
  }
}
and migration :
var Contract1 = artifacts.require("./Contract1.sol");
var Contract2 = artifacts.require("./Contract2.sol");

web3.personal.unlockAccount(web3.eth.accounts[0]);

module.exports = function(deployer) {

	deployer.then(async () => {
		let cont1 = await deployer.deploy(Contract1);
		console.log("address = " + cont1.address);
		let cont2 = await deployer.deploy(Contract2, cont1.address);

		console.log ("there");
		console.log("cont1 " , await cont1.a());
		console.log("cont2 " , await cont2.geta());
	})
}

Deployed by truffle, public transaction.
I found that contracts works good before 22 compiler version. But after 0.4.21 contract hasn't access to another contract storage

**Comment by RomanG11** [comment]
I found the same issue here:
https://github.com/jpmorganchase/quorum/issues/391

**Comment by rjbanner** [comment]
Hi @RomanG11 . Since this issue pertains to Quorum itself and not Quorum Maker, we're closing it.
