### ISSUE TITLE
Cannot Connect Nodes

### ISSUE THREAD

**Issue by BestCharlemagne** [synechron-finlabs/quorum-maker#35]
My problem is that upon page load there is a notification in the top left corner where I can connect new nodes, yet it immediately disappears.  I cannot connect new nodes because of this.

**Comment by dhyansraj** [comment]
Did you get the same behavior on Chrome ? Safari and Firefox is not fully supported yet.

**Comment by BestCharlemagne** [comment]
Yes, the first image is from chrome and the second from firefox.  I created a network on one computer and am attempting to connect from a second, but there is no notification.

After I set up, this is what the console returned: 

For accessing Quorum Maker UI, please open the following from a web browser http://localhost:22004/
To join this node from a different host, please run Quorum Maker and choose option to run Join Network
When asked, enter 192.168.1.30 for Existing Node IP and 22004 for Node Manager Port

Then I connected on the second computer with IP Address of existing being 192.168.1.30 and Node Manager Port of 22004 and IP Address of node being 192.168.1.60 with the rest being default.  However, when I go to http://localhost:22004/ the notification does not appear.


### Chrome
![chrome](https://user-images.githubusercontent.com/17867798/43105374-801f6cb0-8e89-11e8-94b1-a12c9f12c80e.png)
### Firefox
![firefox](https://user-images.githubusercontent.com/17867798/43105376-82936d3e-8e89-11e8-8776-bed57516cc6d.png)

**Comment by dhyansraj** [comment]
Strange Chrome display is messed up like that. What is your display resolution ? Anyway we are adding more logs for you to debug. Please give us couple of days.

**Comment by BestCharlemagne** [comment]
It is at 1360 x 663 and also did not display at 1280 x 1024 but displayed correctly at 1024 x 768

**Comment by dhyansraj** [comment]
Did you get the notification working after the resolution change ?

**Comment by BestCharlemagne** [comment]
Ooops, that was my bad.  My virtual machine was using NAT so the ip address was wrong.  The notification works even when the layout is messed up.  Thank you for helping me out, quorum-maker is awesome!

**Comment by dhyansraj** [comment]
Glad to hear it worked. We are working to get support for more browsers and device. Thanks for using QM. Feel free to report more issues.
