### ISSUE TITLE
metamask get invalid sender error. 

### ISSUE THREAD

**Issue by shiwei12580** [synechron-finlabs/quorum-maker#36]
Hi there. 

I used latest quorum maker, version 2.0.2_2.3  to setup a private network in Aliyun. 

http://47.74.211.253:22204/dashboard

I can connect to truffle console, deploy contract and use truffle to send transactions. 

However, I cannot send transaction from metamask.  it returns a error "invalid sender". 

```
ui.js:1 [ethjs-rpc] rpc error with payload {"id":4841107047314,"jsonrpc":"2.0","params":["0xf86a08808252089497f1fbf68b7f956018236d14251a2a60cc0a6698880de0b6b3a764000080830256aea024cd0f03d5bfd0dab464b8df21931d839ac80da32acb6b5e62d0d3f488584477a00b6ca220b9b1394d44a41dd81c24b88ed87d40ee94e28f0a18f8f677d741864b"],"method":"eth_sendRawTransaction"} Error: invalid sender
```
I also tried to copy the signed message to truffle console and submit using truffle. it returns same error, 
have any one tried to connect to metamask with quorum private chain? I also tried 7nodes example. it returns same error message -- invalid sender. 

Thanks in advance. any hints ?

**Comment by dhyansraj** [comment]
Quorum doesnt support signed transactions mostly due to the privacy implementation and the way Constellations in Quorum work. Could you please confirm this on Slack?

**Comment by shiwei12580** [comment]
thanks @dhyansraj  for the prompt reply. But i am still confused, if I can send transaction from truffle console using truffle-hdwallet-provider. This library is signing the transaction locally on my computer before send the raw transaction to rpc url. 

see the last transaction is from account 0xec02.. while the node coinbase is 0x8abd2 .. 

![image](https://user-images.githubusercontent.com/5944660/43147083-c371b548-8f94-11e8-8fef-a002eb0c8e2e.png)

So in my understanding, quorum should be able to accept signed transaction, which should be a basic functionality to blockchain. 

i guess there should be something wrong with metamask signing this transaction message. is there any special configuration setting i need to pass to metamask before signing.  I have tried 

contractName.defaults({
        gas: 4500000,
        gasPrice: 0
      });

but still no help.

**Comment by dhyansraj** [comment]
I see that this is a public transaction, so should behave exactly as Ethereum would do. When privateFor is used, signed transactions dont work. I still recommend checking with larger group in slack as this doesnt work with 7node example as well.

**Comment by dhyansraj** [comment]
Closing this issue as it may not pertain to QM.
