### ISSUE TITLE
How to update quorum-maker?

### ISSUE THREAD

**Issue by gazambuja** [synechron-finlabs/quorum-maker#41]
Hi, is a easy way to update quorum-maker?
To the last quorum and last quorum-maker version?

thanks

**Comment by dhyansraj** [comment]
If you have setup nodes using an older version of Quorum Maker and looking to upgrade to the latest version, you can do so. If you just want to update to the latest QM, you can pull the latest docker image syneblock/quorum-maker:2.0.2_2.3 and modify the qm.variables file to point to this. If you want to update the Quorum version, you have to build the docker images locally. Please clone https://github.com/synechron-finlabs/quorum-maker-image and update the qm.variables found inside to the correct versions. Run build_image.sh. Go back to Quorum Maker directory and update the qm.variables there to point to the locally built docker image. Also please add below two flags to setup.conf of each node if you upgrading to QM 2.3. 

MODE=ACTIVE
STATE=I
