### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jgege** [synechron-finlabs/quorum-maker#43]
At the moment licensing is undefined for the project. Are you considering choosing one in the near future? :)

(My dissertation will be based on Quorum and so far Quorum Maker looks like the best management tool that is out there.)

**Comment by dhyansraj** [comment]
Lost in versioning. Thanks for bringing up. QM 2.0 is also released under Apache 2.0.

**Comment by dhyansraj** [comment]
License Added
