### ISSUE TITLE
(MacOS) Cannot connect over http to test nodes

### ISSUE THREAD

**Issue by karapish** [synechron-finlabs/quorum-maker#48]
Hello! I'm new to the awesome QM. I am following the quick-start to deploy a test network on my mac. I'm using the latest docker and QM. After running 'docker-compose up' I navigate to the following URLs in chrome\safari without **any** response back. Do I need to configure something extra? I don't have any anti-viruses or firewall apps installed.

http://10.50.0.2:22004
http://10.50.0.3:22004

----- Full copy-paste from the terminal -----
Please select an option: 
 1) Create Network 
 2) Join Network 
 3) Attach to an existing Node 
 4) Setup Development/Test Network 
 5) Exit
option: **4**
Please enter a project name[Default:TestNetwork]:TestNetwork
Please enter number of nodes to be created[Default:3]:
Creating TestNetwork with 3 nodes. Please wait... 
 [################################################## ](100%)
Project TestNetwork created successfully. Please execute docker-compose up from TestNetwork directory
macs-MacBook-Pro:quorum-maker mac$ ls
LICENSE		TestNetwork	doc		lib		setup.sh
README.md	Vagrantfile	img		qm.variables
macs-MacBook-Pro:quorum-maker mac$ cd TestNetwork/
macs-MacBook-Pro:TestNetwork mac$ **docker-compose up**
Creating network "testnetwork_vpcbr" with driver "bridge"
Creating node1 ... done
Creating node3 ... done
Creating node2 ... done
Attaching to node2, node1, node3
node2    | Waiting for Node 1 to deploy NetworkManager contract...
node1    | {"level":"info","msg":"Node Manager listening on :22004...","time":"2018-08-17T00:41:50Z"}
node3    | Waiting for Node 1 to deploy NetworkManager contract...
node1    | {"level":"info","msg":"Deploying Network Manager Contract","time":"2018-08-17T00:41:51Z"}
node2    | {"level":"info","msg":"Node Manager listening on :22004...","time":"2018-08-17T00:41:55Z"}
node3    | {"level":"info","msg":"Node Manager listening on :22004...","time":"2018-08-17T00:41:55Z"}
node1    | {"level":"info","msg":"Adding whitelisted IPs","time":"2018-08-17T00:41:55Z"}
node2    | {"level":"info","msg":"Adding whitelisted IPs","time":"2018-08-17T00:41:57Z"}
node3    | {"level":"info","msg":"Adding whitelisted IPs","time":"2018-08-17T00:41:57Z"}

**Comment by rjbanner** [comment]
Hi @karapish. In the Readme we've mentioned the following regarding test networks on Mac.

Note: If you create a Development/Test Network on Mac, the ports are automatically exported in sequential number, starting 20104, 20204 and so on for each you node created.

Could you  kindly try with these ports

**Comment by karapish** [comment]
Yes! The ports you mentioned do serve html content on Mac. Excuse me for not reading the instructions carefully enough.
