### ISSUE TITLE
How to connect Quorummaker internal network with the LAN network ?

### ISSUE THREAD

**Issue by subhamghosh** [synechron-finlabs/quorum-maker#56]
hi,

I have set up a quorum-maker dev network (setup option 4) using **vagrant** . I am unable to see the dashboard from my host machine. How to get the 2 separate network connection bridged so that I can open the quorum maker dashboard on the host machine and if possible on any machine in the local network ?

**Comment by dhyansraj** [comment]
You can do this by exporting ports using vagrant. This method is explained in the Readme of QM. Please google for advanced use of bride networking in Vagrant. If you still need help, please message me on Quorum slack.
