### ISSUE TITLE
Cannot start two nodes in single machine.

### ISSUE THREAD

**Issue by karthik137** [synechron-finlabs/quorum-maker#63]
I am trying to setup two nodes in the single machine. I have only 4 aws instances. But  i want to setup 6 nodes. I tried to setup two nodes in my local system first. First node started successfully. But second node failed saying "Unknown Error. Please check log. Program exiting".

First node rpc --> localhost:22002

Second node rpc --> localhost:33002 (This one fails to start).

I have checked the scripts. It is not able to fetch genesis data from node manager of the main node. I ran the post manually from the postman and it works. I think the problem is in pre_start_check.sh file.

Attaching screen shot -->
![quroumissuenode](https://user-images.githubusercontent.com/19289544/48221213-7ff3bb00-e3b7-11e8-9195-c14be8abb357.png)

**Comment by karthik137** [comment]
Yes  IP worked. Thanks.

**Comment by karthik137** [comment]
Is it container issue?.

**Comment by dhyansraj** [comment]
no. every machine has same loopback 127.* addresses. So is docker containers. If you ask container to connect to 127.0.0.1, it will connect to itself.
