### ISSUE TITLE
Support tessera

### ISSUE THREAD

**Issue by gtt116** [synechron-finlabs/quorum-maker#68]
Currently, quorum-maker use Constellation as Quorum's transaction manager, adding the support for [Tessera](https://github.com/jpmorganchase/tessera) maybe a good choice.

**Comment by rjbanner** [comment]
We will add Teserra support soon

**Comment by dhyansraj** [comment]
Closing this as Support for Tessera is implemented.

**Comment by paliwalg** [comment]
It continues to run the constellation even after passing the tessera flag.
I have referring to version 2.6.2
