### ISSUE TITLE
Where is the HTML, CSS file for the explorer that's running?

### ISSUE THREAD

**Issue by nobodyme** [synechron-finlabs/quorum-maker#73]
Just like to bring in a small modification on the UI on the explorer and not able to find any HTML, CSS file to bring about the same. May I know where do they reside?

**Comment by dhyansraj** [comment]
QM UI is built on Angular and the source is available at https://github.com/synechron-finlabs/quorum-maker-ui There is also another project https://github.com/synechron-finlabs/quorum-maker-image that can build the UI and bake to docker image.
