### ISSUE TITLE
Nodes Data Does Not Sync On Public Transactions After Docker Images Down

### ISSUE THREAD

**Issue by muhammetevirgen** [synechron-finlabs/quorum-maker#76]
I'm running a 4 nodes setup with QM, each on a different Ubuntu machine on Amazon. I am trying some test cases.
When ı create a network from scratch with 1 creator and 3 joiner, everything is fine.

But when ı want to test if 1 of the node goes down (removing docker contanier) and trying to rejoin network with same node name and IP address the nodes come back successfully but the data is not synced.
 
I am runnnig start.sh under nodename folder , node come back but the data is not synced from the creator node or from any other. 

Is there a way to rejoin existing network with same IP and same node name with whole data sync ?

**Comment by dhyansraj** [comment]
Are you joining the same node using 2. Join network option again? Once joined, you are only supposed to stop and start node, not join again. You can change to respective node directory and execute ./start.sh to bring the node up. 

When you create the first node, it has already ahead in 2 transactions (Node Manager contract deployment and self register transaction). When you join the second node, it must have synced the chain and caught up the blocks. After joining the second node, you would mostly see 3 blocks on all 2 nodes. So I believe chain syncing is happening correctly (If not you wont be able to see both nodes correctly on the UI). 

Please let me know the steps you followed in details so that I can help you further.

**Comment by muhammetevirgen** [comment]
Hi Again,

What I have done is , I have re run my test setting up 3 nodes correctly, there was no sync problem at begining.
Afterward I have deployed my own test contract and which went well on all nodes, all nodes was synced and had 8 blocks in my example.
Then I reboot one of the node (which will cause to docker stop I think , I dont see anything on docker ps -a after reboot),
and all others lost connection on healtcheck as expected.
After reboot, I enter the node directory folder and run  start.sh command to start node again.
When I check the  UI on rebooted node, I see that other 2 nodes are getting heartbeart from new comer and update the node count as 3.
But the main problem is,on the UI for rebooted node there is no block. 

I am attaching the list below.

1) QM UI screenshot of rebooted node after reboot(Rebooted_Node_UI_Screenshot.png)
2) QM UI screenshot of node1 which is creator node(Creator_Node_UI_Screenshot.png)
3) QM UI screenshot of node2 which is another healthy node on network(Second_Node_UI_Screenshot.png)
2) Geth log of rebooted node  (Rebooted_Node_Geth_Log.txt)
3) Geth log creator node (Creator_Node_Geth_Log.log.txt)
4) Geth log of second node (Second_Node_Geth_Log.log.txt)


[Rebooted_Node_Geth_Log.txt](https://github.com/synechron-finlabs/quorum-maker/files/2820662/Rebooted_Node_Geth_Log.txt)
<img width="923" alt="creator_node_ui_screenshot" src="https://user-images.githubusercontent.com/15906769/52110622-3c08fe80-2612-11e9-9da2-db7cb4c3d67f.png">
<img width="905" alt="second_node_ui_screenshot" src="https://user-images.githubusercontent.com/15906769/52110623-3ca19500-2612-11e9-9e88-a8080569bf7e.png">
<img width="928" alt="rebooted_node_ui_screenshot" src="https://user-images.githubusercontent.com/15906769/52110624-3ca19500-2612-11e9-8ab3-f578db217a76.png">
[Creator_Node_Geth_Log.log.txt](https://github.com/synechron-finlabs/quorum-maker/files/2820663/Creator_Node_Geth_Log.log.txt)
[Second_Node_Geth_Log.log.txt](https://github.com/synechron-finlabs/quorum-maker/files/2820664/Second_Node_Geth_Log.log.txt)

**Comment by dhyansraj** [comment]
When you rebooted the node, did the IP change ? Is this hosted on cloud?

**Comment by muhammetevirgen** [comment]
This host is on cloud but I  have static IP address so IP address of host did not change after reboot

**Comment by dhyansraj** [comment]
This issue is related to #87 and is fixed now. Can you try again?

**Comment by muhammetevirgen** [comment]
I tried again and looks issue is fixed !

**Comment by muhammetevirgen** [comment]
Fixed
