### ISSUE TITLE
Truffle does not migrate contracts to QM

### ISSUE THREAD

**Issue by stefanionescu** [synechron-finlabs/quorum-maker#77]
In my migrations file I do the following:

https://gist.github.com/stefanionescu/6f0b2f565c34956f4e91cb35ddff77fb

Before migrating I unlock the first node with this code:

https://gist.github.com/stefanionescu/24e60d6ffa97011d2b921be47e91c950

Regardless, when I migrate to "node1Public", I don't see the transactions in QM. Do I do something wrong?

**Comment by rjbanner** [comment]
You may need to downgrade Truffle to v4.1.x or try https://github.com/trufflesuite/truffle/pull/1806
Also can you confirm that the port in truffle actually maps to what was set up in quorum-maker

**Comment by rjbanner** [comment]
Please reopen this if this solution does not work
