### ISSUE TITLE
Pending transtractions are stucked in some node

### ISSUE THREAD

**Issue by colindog** [synechron-finlabs/quorum-maker#80]
I setup a testnet with 11  nodes.
And then keep sending test transactions to some nodes.
But after some time, the pending queue of some node is stucked like:

> txpool.status
{
  pending: 10413,
  queued: 0
}

And this node stops dealing with new transactions.
But the other nodes works well.
I met this for several times but cant find the reason.
Can someone please help to analyse this?

**Comment by dhyansraj** [comment]
Is this node still connected to the network? Can you see it in the network list on QM UI? If so this could be a Quorum problem and better to raise in the Quorum stack. QM doesnt do much than forming the network and rest is done through Quorum.

**Comment by colindog** [comment]
Thanks. I raised the issue to JP Quorum.
