### ISSUE TITLE
Make the joined node the master

### ISSUE THREAD

**Issue by naveen-appoets** [synechron-finlabs/quorum-maker#83]
So I synced up two nodes. First I created a node then a setup a second node to join the network and sync went fine but later when I deleted the first node. The second node is no longer forming blocks of it's own and hence a lot of pending transactions and transaction underpriced error comes up. Any help would be appreciated.

**Comment by dhyansraj** [comment]
Delete node is not supported by QM out of the box. You should manually do a raft.removePeer before deleting the directories.

**Comment by dhyansraj** [comment]
You need to connect to the geth console. You do this by first getting to docker container console and then getting into geth console. 
1. docker exec -it <nodename> bash
2. geth attach qdata/geth.ipc

**Comment by naveen-appoets** [comment]
Thank you, will try.

**Comment by naveen-appoets** [comment]
Sorry about this but where would I find the raftID for the concerning peer I would like to remove? Since that is passed as the argument to raft.removePeer?
