### ISSUE TITLE
Node Manager not starting in live network

### ISSUE THREAD

**Issue by stefanionescu** [synechron-finlabs/quorum-maker#85]
Hi!

I'm trying to setup a network between multiple machines in my office. When I create my first node in the network, it stops after saying "When asked, enter 10.0.2.15 for Existing Node IP... ".

It looks like this:

![failed_net](https://user-images.githubusercontent.com/15263515/52340888-eb761480-2a08-11e9-9e66-318bdcfa6671.png)

It doesn't show the Node Manager starting and when I try to access the UI, it doesn't work.

**Comment by dhyansraj** [comment]
Looks like the Geth is not starting probably waiting forever for Constellation to start. Please check the geth and constellation logs.

**Comment by stefanionescu** [comment]
I think I solved the problem, I wasn't specifying a correct ip
