### ISSUE TITLE
Transactions involving arrays are always reverted

### ISSUE THREAD

**Issue by stefanionescu** [synechron-finlabs/quorum-maker#86]
Hi, I made a smart contract where I store strings in an array. 

In my truffle tests everything works fine but when I submit a transaction with web3Quorum, it always reverts.

The same thing happens with struct arrays

[EDIT] Also cannot store stuff in nested mappings

**Comment by dhyansraj** [comment]
Is the truffle tests work fine with QM? If so, it could be a problem with Quorum. Do you know if web3Quorum works fine with 7 node example?

**Comment by stefanionescu** [comment]
All truffle tests work perfectly. I didn't try the 7 nodes example but either way, the contracts should work on any custom network

**Comment by rjbanner** [comment]
You may need to downgrade Truffle to v4.1.x

**Comment by stefanionescu** [comment]
Thanks!

**Comment by rjbanner** [comment]
Please reopen this if this solution does not work
