### ISSUE TITLE
Block structure is not preserved after dev network is revived

### ISSUE THREAD

**Issue by dogayuksel** [synechron-finlabs/quorum-maker#87]
- I clone quorum-maker repository (syneblock/quorum-maker:2.2.1_2.6.2)
- I run the following commands
`./setup.sh dev -p testchain -n 3 -e`
`cd testchain`
`docker-compose up -d`
- I check the quorum-maker dashboard, all looks good.
![screenshot-1](https://user-images.githubusercontent.com/1379086/53016633-559da900-344e-11e9-9e00-66e4b8b03555.png)

- then I stop the network with the following command
`docker-compose down`

- when I bring the network up with `docker-compose up -d`, I see all transactions *concatenated into one block* on the dashboard.
![screenshot - 2](https://user-images.githubusercontent.com/1379086/53016647-60583e00-344e-11e9-8bc4-3105f03ab2d2.png)

I tried to `docker commit` each node's container to an image and docker compose up from those but the result is the same.

Do you have any idea how to review the network properly?

**Comment by dhyansraj** [comment]
We are actively looking into this problem. Will get back to you soon.

**Comment by dhyansraj** [comment]
We found a solution and seems to be working. The fixes are pushed to same branch. Can you try again?

**Comment by dogayuksel** [comment]
Works great, thank you very much.
