### ISSUE TITLE
not able to join node without GUI

### ISSUE THREAD

**Issue by jashradia** [synechron-finlabs/quorum-maker#88]
I am using ubuntu servers on which I have to setup quorum network that has no GUI (GNOME).
node 1 IP = 10.14.6.7
node 2 IP = 10.14.6.4
I was able to create a node (node 1) but then when I tried to join a node (node 2) to an existing network, it gave me a message that "join request is sent to node 10.14.6.7, waiting for approval" which is IP of node 1.
On on node 1's terminal it gave me a message that "join request received from 10.14.6.4" which is IP of node 2.

But the issue is that i can not approve of accept this invitation of joining node from CLI. I tried to search a lot in your wiki and docs but there were only 2 ways.

    from GUI
    from email

so in my ubuntu server there is no GUI so i can not open localhost webpage in my quorum node. There should be another way to accept a joining node's approval rather than only using GUI to do it. otherwise I won't be able to use quorum-maker in my ubuntu servers.

If there is a way to approve a joining node from CLI then do tell me and if not, then you should add that feature for everyone who is using servers without GUI.

**Comment by dhyansraj** [comment]
wont you be able to connect to http://10.14.6.7:<nodeManagerPort> from internet or a machine with GUI that can access this IP ? If you are using cloud servers, you can use the public IP to connect to this machines. Allow ingress for NodeManagerPort. 

Another option is whitelisting the IP addresses, so join requests are automatically approved. 

Use following command to add nodes to main nodes whitelist.

curl --header "Content-Type: application/json" --request POST --data '10.14.6.4'  http://10.14.6.7:<NodeManagerPort>/updateWhitelist

**Comment by jashradia** [comment]
Thanks, whitelisting solves it
