### ISSUE TITLE
The timestamp of the block is wrong

### ISSUE THREAD

**Issue by colindog** [synechron-finlabs/quorum-maker#89]
I use qm to create a testnet.
But I found that the timestamp of the block is wrong.
The timestamp is like : 1551448095094126300.
But it should be  1551448095 .
Do you met the similiar problem?

**Comment by dhyansraj** [comment]
what do you see from the geth console ?

**Comment by colindog** [comment]
The timestamp I mentioned is read from the geth console. Have you ever met this?

**Comment by colindog** [comment]
I find the reason. This is normal because quorum use nanoseconds in RAFT.
