### ISSUE TITLE
Exec format error in Quorum-maker on Raspberry Pi

### ISSUE THREAD

**Issue by jashradia** [synechron-finlabs/quorum-maker#90]
I was trying to set up quorum-maker for R Pi. 
I ran the command ./setup.sh --help
it downloaded some docker images but then I get the following error output...
.
standard_init_linux.go:207: exec user process caused "exec format error"

How to solve this?

**Comment by dhyansraj** [comment]
We never tested on Pi. --help is a simple shell scripts, no Quorum or Tessera started. Is other ubuntu 160.4 images work fine ?

**Comment by jashradia** [comment]
The same error occurs whether i start normal setup script with --help or without. While downloading, it gets some images, then Digest : "some hash value" comes and then it shows this error

**Comment by jashradia** [comment]
Yes i can not download any quorum image that is compatible with Raspberry Pi. Do you know if it is in the roadmap for quorum to develop ARMv7 linux compatible images ?

**Comment by rjbanner** [comment]
@jashradia you can try the official Quorum slack for any roadmap queries
